FROM cadc-tomcat:latest

## cavern specific

# cavern needs:
# - sssd-client 
# - acl
# but they are already installed in cadc-tomcat so nothing to do

COPY build/libs/cavern.war /usr/share/tomcat/webapps/

